--BASIC
require('core.plugins')
require('core.mappings')
require('core.config')
-- require('core.autocmd')

--PLUGINS
require('plugins.neotree')
require('plugins.tokyonight')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.telescope-fzf-native')
-- require('plugins.null-ls')
require('plugins.dashboard')
require('plugins.lualine')
require('plugins.bufferline')
require('plugins.comment')
require('plugins.imagepreview')
require('plugins.gitsigns')
require('plugins.hop')
require('plugins.toggleterm')
-- require('plugins.signature')
require('plugins.leap')
require('plugins.kanagawa')
require('plugins.catpucin')
-- require('plugins.onenord')
require('plugins.inlayhints')
require('plugins.lsp-installer')
-- require('plugins.centerpad')
require('plugins.transperent')
require('plugins.better-escape')
require('plugins.cpp-tools')
require('plugins.file-browser')
require('plugins.treesj')
require('plugins.overseer')
require('plugins.lspkind')
require('plugins.hlargs')
require('plugins.snippets')
require('plugins.material')
require('plugins.barbecue')
require('plugins.cursorline')
-- require('plugins.pretty-fold')
-- require('plugins.foldsign')
require('plugins.origami')
require('plugins.ibl')
